madek_master_secret: 'secret'

# madek_api_session_enabled: true is hardcoded now
# madek_session_cookie_name 'madek-session' is hardcoded now
madek_session_validity_duration: 7 days


database: {}

services:

  api:

    cors_enabled: true
    admin_enabled: true
    user_enabled: true
    is_reloadable: true

    http:

      host: localhost
      port: 3104
      context: ""
      sub_context: ""
      ssl: false

    nrepl:
      port: 7802
      bind: "127.0.0.1"
      enabled: true


