- name: apt unzip
  apt:
    name: unzip
    state: present

- name: copy jar
  copy:
    src: "{{role_path}}/../../../madek-api-v2.jar"
    dest: "{{madek_api_v2_dir}}/madek-api-v2.jar"
    owner: root
    mode: 0644

