- name: api-v2 directory
  file:
    path: /var/www/madek-api-v2
    state: directory
    mode: 0755

- name: disabled page HTML
  template:
    src: disabled.html
    dest: /var/www/madek-api-v2/503.html
    mode: 0644

- name: disabled page config
  template:
    src: disabled.conf
    dest: /etc/apache2/madek/conf.d/madek_800_api_v2.conf
    mode: 0644

- name: reload reverse-proxy
  service:
    name: apache2
    state: reloaded
